### ISSUE TITLE
Docs for app, installation, and operation

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#17]
Use wiki pages for these docs.

**Comment by eightysteele** [comment]
Keep these docs simple. Target developers. Could even be README in source tree.

**Comment by eightysteele** [comment]
@tucotuco: Update the wiki to be in sync with your recent `sdl.py` badassery: https://github.com/eightysteele/Spatial-Data-Library/wiki/Cell-Processing-Workflow

**Comment by tucotuco** [comment]
Updated Cell-Processing-Workflow wiki, including short reference on couchutils.py for CouchDB management.
