### ISSUE TITLE
Convert Worldclim outputs to SI units

### ISSUE THREAD

**Issue by tucotuco** [eightysteele/Spatial-Data-Library#20]
Worldclim values are stored in their native form in CouchDB (e.g., temperatures are given as degrees times 10). Convert these values server-side to standard SI units and make them accessible directly through these converted units in memcache.

The conversions are:
Temperatures: divide by 10 for degrees Celsius
Altitude: no change, already in m
Precipitation: no change, already in mm
Bio1: Annual Mean Temperature, divide 10 for degrees Celsius
Bio2:  Mean Diurnal Range (Mean of monthly (max temp - min temp)), divide 10 for degrees Celsius
Bio3: Isothermality (BIO2/BIO7) (\* 100), this is a percent, divide by 100 for unitless result
Bio4: Temperature Seasonality (standard deviation *100), divide 100 for degrees Celsius
Bio5: Max Temperature of Warmest Month, divide 10 for degrees Celsius
Bio6: Min Temperature of Coldest Month, divide 10 for degrees Celsius
Bio7: Temperature Annual Range (BIO5-BIO6), divide 10 for degrees Celsius
Bio8: Mean Temperature of Wettest Quarter, divide 10 for degrees Celsius
Bio9: Mean Temperature of Driest Quarter, divide 10 for degrees Celsius
Bio10: Mean Temperature of Warmest Quarter, divide 10 for degrees Celsius
Bio11: Mean Temperature of Coldest Quarter, divide 10 for degrees Celsius
Bio12: Annual Precipitation, no change, already in mm
Bio13: Precipitation of Wettest Month, no change, already in mm
Bio14: Precipitation of Driest Month, no change, already in mm
Bio15: Precipitation Seasonality (Coefficient of Variation), no change, unitless
Bio16: Precipitation of Wettest Quarter, no change, already in mm
Bio17: Precipitation of Driest Quarter, no change, already in mm
Bio18: Precipitation of Warmest Quarter, no change, already in mm
Bio19: Precipitation of Coldest Quarter, no change, already in mm

**Comment by eightysteele** [comment]
Done. Closing issue pending feedback.

**Comment by tucotuco** [comment]
+1
