### ISSUE TITLE
Variable aliases to conserve space

### ISSUE THREAD

**Issue by tucotuco** [eightysteele/Spatial-Data-Library#25]
There are 353 characters in the 68 Worldclim variable names. The storage for each entity in the datastore includes this overhead. So for ~183M terrestrial that's 60GB of storage required for variable names. At $0.17 cents per GB per month, that's $10.23 per month.

With a dictionary mapping between variable names and a shorter alias name (see https://gist.github.com/1130968), we can reduce the variable name storage to 157 characters (26.8GB, $4.55 per month).

Interesting metric: every character in Worldclim entities costs $0.03 per month.

**Comment by eightysteele** [comment]
Are your calculations above factoring in 1 or 2 bytes for the UTF-8 characters? Also, the gist above might be more readable if you change the language from plain text to Python.

**Comment by tucotuco** [comment]
Based on 1 byte per character. Gist language changed to Python.

**Comment by eightysteele** [comment]
> Based on 1 byte per character. Gist language changed to Python.

+1

**Comment by tucotuco** [comment]
Changes implemented to save space:
aliases on vars (127 vs 370)  (t1, t2, m1,m2,x1,x2,b1,b2,a1,a2,p1,p2)
coordinates (<=46 vs 135) (bounding boz with stripped zeros vs polygon without stripped zeros)

Net savings of at least 332 characters ($9.60) per record month.

**Comment by eightysteele** [comment]
+1
