### ISSUE TITLE
Enable Terabyte drive on eightysteele.berkeley.edu

### ISSUE THREAD

**Issue by tucotuco** [eightysteele/Spatial-Data-Library#26]
Says it all.

**Comment by eightysteele** [comment]
Mounted at `/media/sdb` and is reserved for the CouchDB instance.

**Comment by tucotuco** [comment]
No terrorbytes: 
tuco@vlsb-3186-1:/media/sdb$ df .
Filesystem 1K-blocks Used Available Use% Mounted on
/dev/sda2 223856640 170149580 42335724 81% /t

Adding to CouchDB affects available space not on /media/sdb, but instead on /dev/sda2, which shows only 218GB of total storage and has only 19% remaining.

**Comment by eightysteele** [comment]
Yeah, bummer, `/dev/sdb` is where the drive is but it has an invalid partition table: https://gist.github.com/1134246

I'll have to work on this onsite tomorrow via live cd, but will scan in the meantime for any quick workarounds.
