### ISSUE TITLE
Add GAE range bulkloading to sdl.py

### ISSUE THREAD

**Issue by tucotuco** [eightysteele/Spatial-Data-Library#28]
While processing the cells coming out of starspan in sdl.py, build the range lists and bulkload them to App Engine.

**Comment by eightysteele** [comment]
Changed issue label to Priority-Critical and Status-Accepted.

**Comment by eightysteele** [comment]
Done: https://github.com/eightysteele/Spatial-Data-Library/commit/3acbfc195166239d27845697ae5e61710bfafe37

@tucotuco: Request code review.

**Comment by tucotuco** [comment]
LGTM. Wanna see it in action on some streamlined cells. We ready for
me to do that?

On Tue, Aug 9, 2011 at 11:40 PM, eightysteele
reply@reply.github.com
wrote:

**Comment by eightysteele** [comment]
Pull the trig against canary at the /ah/remote_api endpoint. Test locally
first for fun.
On Aug 10, 2011 12:31 AM, "tucotuco" <
reply@reply.github.com>
wrote:
