### ISSUE TITLE
CSV for WorldClim layer metadata

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#29]
Put together a CSV for all Worldclim layer variable metadata. We need that for the variables API. Maybe we can ping RJH for this if he has it (to save us a little work)?

**Comment by tucotuco** [comment]
Wrote the tools/worldclimhdrreader.py to grab the high-res layers, read through the .hdr files, extract the min and max values for all variables and construct the metadata json (final output at https://gist.github.com/1152668) for all variables.

**Comment by eightysteele** [comment]
Nice job. +1

**Comment by tucotuco** [comment]
Make a csv file for variable metadata to replace the json file https://github.com/eightysteele/Spatial-Data-Library/blob/master/tools/python/worldclimmetadata.json.

**Comment by tucotuco** [comment]
New CSV file added. https://github.com/eightysteele/Spatial-Data-Library/blob/master/tools/python/worldclimmetadata.csv
