### ISSUE TITLE
Mod sdl.py to save couchdb csv files

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#31]
The `sdl.py` script needs to save the CSV files that are used to bulkload data to CouchDB. These files will then be used in the same script to bulkload `CellIndex` entities to App Engine. These files are needed since they contain all variable values per cell which is a requirement for building `CellIndex` entities with multi-variable intervals.

**Comment by tucotuco** [comment]
sdl.py modified to save these files in a folder called forcouch inside the directory set at runtime for the workspace parameter.
Workspace can now be independent on every run so that Tiles can be divided up onto areas with minimal marine environs where there are no variable values.

**Comment by eightysteele** [comment]
+1
