### ISSUE TITLE
Create 15 kilometer buffer around GADM shapefile

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#6]
Create new version of our GADM file with a 15 kilometer buffer. Here's the GADM we're using:

http://geocommons.com/overlays/33578

**Comment by eightysteele** [comment]
Was pushed to: https://github.com/eightysteele/Spatial-Data-Library/blob/master/data/Countries15kBuffered.tar.gz

**Comment by eightysteele** [comment]
Modified shapefile by merging all country features into a single polygon: Terrestrial15kBuffer.shp

**Comment by tucotuco** [comment]
+1 What did you use to merge?

**Comment by eightysteele** [comment]
> +1 What did you use to merge?

QGIS has a 'merge features' feature. I used that.

**Comment by tucotuco** [comment]
This has been found to be a bad idea. A new terrestrial layer based on actual Worldclim data has been integrated in the workflow. This minimizes processing to only cells that have data.
