### ISSUE TITLE
Bulkload global 1k cells to CouchDB

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#7]
Title says it all!

**Comment by eightysteele** [comment]
New TB drive installed on dev server. New tools/python/src/sdl.py script complete. Bulkload process started for bulkloading 1k cells to CouchDB for worldclim tile 37.

**Comment by eightysteele** [comment]
Waiting for production server options from @vdave.

**Comment by eightysteele** [comment]
Maybe we should go with this:
http://www.iriscouch.com

**Comment by tucotuco** [comment]
Tile 11 loaded, zerovals removed, and api/cells view built at http://spatial.iriscouch.com/_utils/database.html?worldclim/_all_docs

Will load the rest when Issue 25 and Issue 27 are closed.

**Comment by eightysteele** [comment]
@tucotuco started this process which is bulkloading to our iris couch instance.

**Comment by tucotuco** [comment]
ETA for tiles processed to CouchDB- and GAE-ready csv files is 20 Sep. Total elapsed time for prep approx one month running two tiles at a time.

**Comment by tucotuco** [comment]
All 156000409 cells uploaded to spatial.iriscouch.com into worldclim database.
