### ISSUE TITLE
Research bounding box spatial queries on App Engine

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#8]
This is for querying specimen points within a bounding box. Currently a few different options:

http://code.google.com/apis/maps/articles/geospatial.html
http://code.google.com/appengine/articles/geosearch.html

Native geo queries also in the works:

http://www.google.com/events/io/2011/sessions/full-text-search.html

**Comment by eightysteele** [comment]
Extend API with `bb` parameter and return all cells within it.

**Comment by tucotuco** [comment]
RMGCell.cells_in_bb() returns a set() of cell keys given a nwcorner and a se corner of a bounding box.

https://github.com/eightysteele/Spatial-Data-Library/blob/master/sdl/rmg.py#L270

**Comment by eightysteele** [comment]
+1
